
services:
    # container name
    api:
        build: .
        depends_on:
            - postgres
        ports:
            # port on localhost: port on container
            - 8000:8000
        volumes:
                #adding it because when we change the code, it wont change in the container so our api wont change, so we will copy the machine files into our container, bind mount
            - ./:/user/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
        # env_file:
        #   - ./.env 
        environment:
            - DATABASE_HOSTNAME=host.docker.internal
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=7364
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        

    postgres:
        image: postgres
        environment:
            # correct variables (mapping format)
            POSTGRES_PASSWORD: 7364
            POSTGRES_DB: fastapi
        # volumes so that we save container data on our local machine and when
        # the container goes down or is deleted, the data will be safe
        volumes:
            - postgres-db:/var/lib/postgresql/data # path of the container

volumes:
    postgres-db:
